### ISSUE TITLE
There doesn't appear to be an ability to use UserContextData

### ISSUE THREAD

**Issue by leepa** [aws/aws-sdk-net-extensions-cognito#101]
### Describe the feature

I would like to be able to pass the UserContextData related to the user to the auth flow request as documented in the InitiateAuth API documentation.

### Use Case

I want to be able to use the Advanced Security Features of Cognito with the SRP flow

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS .NET SDK and/or Package version used

AWSSDK.CognitoIdentity 3.3.0.0
AWSSDK.CognitoIdentityProvider 3.3.0.0
AWSSDK.Core 3.3.0.0
AWSSDK.SecurityToken 3.3.0.0

### Targeted .NET Platform

.NET 6

### Operating System and version

macOS, Linux

**Comment by ashishdhingra** [comment]
Hi @leepa,

Good morning.

Thanks for raising feature request. Could you please share more details from Cognito documentation which specifies support for user context data? Kindly review if you are referring to `ClientMetadata` as implemented by the pending PR https://github.com/aws/aws-sdk-net-extensions-cognito/pull/90.

Thanks,
Ashish
