### ISSUE TITLE
CognitoUser.ListDevicesAsync() doesn't support returning pagination token.

### ISSUE THREAD

**Issue by erikkanderson** [aws/aws-sdk-net-extensions-cognito#106]
### Describe the feature

This feature request is specific for UserAuthentication.CognitoUser's ListDevicesAsync() method.

Current this method takes a limit (number of devices to return) and a continuation token (to presumable retrieve the next set of devices attached to a user). The limitation of the current implementation is, ListDevicesAsync() only returns the list of devices, it does not return the call's continuation token. Without the initial call to ListDevicesAsync()'s continuation token, it's not possible to get the next set of devices and subsequent calls. 

### Use Case

To retrieve a complete list of a user's devices, when the user has more than 60 (the maximum limit) devices.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS .NET SDK and/or Package version used

Amazon.Extensions.CognitoAuthentication version 2.3.0

### Targeted .NET Platform

netstandard2.0 netstandard2.1

### Operating System and version

Windows 11

**Comment by ashishdhingra** [comment]
Just for reference, [CognitoUser.ListDevicesAsync()](https://github.com/aws/aws-sdk-net-extensions-cognito/blob/2e370fcc216078d772eba8057f49f2a76aded759/src/Amazon.Extensions.CognitoAuthentication/CognitoUser.cs#L362) doesn't have ability to return [PaginationToken](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_ListDevices.html#API_ListDevices_ResponseSyntax) as mentioned in the [ListDevices](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_ListDevices.html) API reference.

@erikkanderson Feel free to contribute the feature request. However, changing return signature would be a breaking change and method overloading doesn't consider return types. May be adding a similarly named method, e.g. `ListDevicesWithPaginationTokenAsync` might be helpful!

**Comment by ashishdhingra** [comment]
We have implemented new `ListDevicesV2Async` method in [Amazon.Extensions.CognitoAuthentication version 2.4.0](https://www.nuget.org/packages/Amazon.Extensions.CognitoAuthentication/2.4.0) which allows listing additional pages of devices. The response returned from this method contains `DeviceType` objects which could be used to construct list of `CognitoDevice` type objects and a `PaginationToken` which could be used to access remaining device types (if any).

**Comment by erikkanderson** [comment]
Just implemented a call with ListDeviceV2Async, works great. Thank you.
