### ISSUE TITLE
`CognitoAuthHelper.GetAssemblyFileVersion` Expensive CPU Wise

### ISSUE THREAD

**Issue by mojotheo** [aws/aws-sdk-net-extensions-cognito#107]
### Describe the bug

We’ve noticed some issues with the AWS Cognito Dotnet Library in terms of performance. We were having some performance issues on our server, and upon investigation, every Cognito call that we make calls a function `CognitoAuthHelper.GetAssemblyFileVersion` that is rather expensive since it reads an Assembly to get the version and send it back to AWS for metrics.
As shown in the flame graph below, it’s taking around 77ms of CPU time, (which in the case of this endpoint we make 3 cognito calls, which accounts for 90%+ of the CPU time). It also reads it every single time we make a call instead of caching the version, which would stay unchanged if the process is never restarted.
![Cognito Flame Graph](https://user-images.githubusercontent.com/106850274/223257799-4af69ad6-017a-495f-9c45-3df4ba7dbf86.png)

### Expected Behavior

Not have a CPU expensive call everytime there is a Cognito Call

### Current Behavior

Every Cognito API call causes a large block when attempting to read an assembly file

### Reproduction Steps

Any call to Cognito SDK will cause the issue

### Possible Solution

Disable the call to get the AssemblyFileVersion, or cache the version 

### AWS .NET SDK and/or Package version used

AWSSDK.Core v3.7.13.10

### Targeted .NET Platform

.NET Core 3.1

### Operating System and version

Windows Server 2019, Mac OS Ventura

**Comment by mojotheo** [comment]
@ashishdhingra Yep! Here you go: https://github.com/aws/aws-sdk-net-extensions-cognito/pull/108

**Comment by mojotheo** [comment]
@ashishdhingra When do you expect the team to have a path forward with this? We need to know if we should pursue a work around in the mean time.

**Comment by ashishdhingra** [comment]
Released in [Amazon.Extensions.CognitoAuthentication version 2.3.1](https://www.nuget.org/packages/Amazon.Extensions.CognitoAuthentication/2.3.1)
