### ISSUE TITLE
Async methods should ALWAYS accept an optional cancellation token

### ISSUE THREAD

**Issue by GabrielHare** [aws/aws-sdk-net-extensions-cognito#113]
### Describe the feature

Feature: All async methods should accept an optional cancellation token.

Examples of methods that do not satisfy these requirements:
- StartWithSrpAuthAsync
- StartWithRefreshTokenAuthAsync

Pertains to package version 2.4.0 (latest version on NuGet as of this time)

### Use Case

Observation: authorization requests NEVER timeout - even if there is no network connection. I have tried waiting for an hour, and the authorization will just wait until enable a network connection.

Use-case: If an application is running with NO network connection, a thread that awaits an authorization request will never restart. However, if the authorization is a background task it cannot be cancelled, so an IDisposable pattern can't work and a resource leak is likely. Furthermore, the standard SDK methods all accept cancellation tokens, so this pattern change is really odd.

Work-around: Use the SDK source code and make the necessary changes.

### Proposed Solution

Have an optional CancellationToken argument in the StartWithSrpAuthAsync method. Pass this to the invoked SDK methods (which already have optional cancellation tokens).

That's all it would take... just stick with the existing design pattern. Since the arguments are optional no code that currently uses these methods would need to change.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS .NET SDK and/or Package version used

AWS SDK Extensions for .NET Standard 2.0 (compatible with .NET Framework 4.5)
Version 2.4.0
https://www.nuget.org/packages/Amazon.Extensions.CognitoAuthentication/

### Targeted .NET Platform

.NET Framework 4.5

### Operating System and version

Ubuntu 22.04

**Comment by ashishdhingra** [comment]
Appears to be a valid feature request following the standard `async` method signature.

**Comment by GabrielHare** [comment]
[Requested Pull Request](https://github.com/aws/aws-sdk-net-extensions-cognito/pull/115)

**Comment by GabrielHare** [comment]
Looking at the PR I noticed that some CR / NL changes occurred. I think it's in the direction that is consistent with the project...

**Comment by ashishdhingra** [comment]
@GabrielHare Thanks for the contribution. The change has been released in [Amazon.Extensions.CognitoAuthentication version 2.4.1](https://www.nuget.org/packages/Amazon.Extensions.CognitoAuthentication/2.4.1)
