### ISSUE TITLE
Include support for AnalyticsMetadata in initiateAuthRequest and InitiateSRPAuthrequest

### ISSUE THREAD

**Issue by rajneeshmadan** [aws/aws-sdk-net-extensions-cognito#147]
### Describe the feature

In Cognito provider with initiateAuthRequest and other API.. AnalyticsMetadata is supported but is not added in this extension. 

### Use Case

For Pinpoint Analytics this field is required 

### Proposed Solution

Change InitiateAuthRequest and InitiateRequest to add Analyticsmetatdata attribute as well (similare to clientmetadata)

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS .NET SDK and/or Package version used

AWS SDK

### Targeted .NET Platform

.Net framework 4.7

### Operating System and version

Windows

**Comment by bhoradc** [comment]
Hello @rajneeshmadan, 

Thank you for submitting this feature request. This looks a reasonable ask especially when the Cognito API (e.g. [InitiateAuthRequest](https://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/CognitoIdentityProvider/TInitiateAuthRequest.html)) supports the `Analyticsmetatdata` property. 

I will further review this with the .NET SDK team. Thank you.

Regards, 
Chaitanya

**Comment by rajneeshmadan** [comment]
Thanks for working on this.. I see PR is still not merged. Please help by prioritizing it.

**Comment by ashishdhingra** [comment]
Changes released in [Amazon.Extensions.CognitoAuthentication 2.5.5](https://www.nuget.org/packages/Amazon.Extensions.CognitoAuthentication/2.5.5).
