### ISSUE TITLE
DeviceKey is being added twice to challenge request in CognitoUser.StartWithSrpAuthAsync

### ISSUE THREAD

**Issue by timadamson** [aws/aws-sdk-net-extensions-cognito#23]
In CognitoUser.StartWithSrpAuthAsync DeviceKey is being added twice to challenge request causing "An item with the same key has already been added" exception

## Expected Behavior
StartWithSrpAuthAsync with a DeviceKey does not throw an exception

## Current Behavior
The DeviceKey is added to the challenge request in CreateSrpPasswordVerifierAuthRequest and then again in StartWithSrpAuthAsync, causing a "An item with the same key has already been added" exception

CognitoUser.StartWithSrpAuthAsync
```
bool challengeResponsesValid = challengeRequest != null && challengeRequest.ChallengeResponses != null;
bool deviceKeyValid = Device != null && !string.IsNullOrEmpty(Device.DeviceKey);

if (challengeResponsesValid && deviceKeyValid)
{
    challengeRequest.ChallengeResponses.Add(CognitoConstants.ChlgParamDeviceKey, Device.DeviceKey);
}
```

CognitoUser.CreateSrpPasswordVerifierAuthRequest
```
if (Device != null && !string.IsNullOrEmpty(Device.DeviceKey))
{
    srpAuthResponses.Add(CognitoConstants.ChlgParamDeviceKey, Device.DeviceKey);
}
```

## Possible Solution
Only add DeviceKey once

## Steps to Reproduce (for bugs)
Call StartWithSrpAuthAsync with a DeviceKey in the CognitoUser object

**Comment by assyadh** [comment]
This issue has been fixed as part of https://github.com/aws/aws-sdk-net-extensions-cognito/commit/bbc87808be5a14950bf8210a79770a4261a4ac23
