### ISSUE TITLE
StartWithSrpAuthAsync() can throw PasswordResetRequiredException() on login

### ISSUE THREAD

**Issue by iainb123** [aws/aws-sdk-net-extensions-cognito#25]
The Amazon.Extensions.CognitoAuthentication.CognitoUser will throw a PasswordResetRequiredException on login if the user's password has been reset in Cognito.  It is not possible to start the ResponseToNewPasswordRequiredAsync() as there's no SessionID available yet (as an exception was thrown, rather than returned on the Task). 

## Expected Behavior

The exception should be suppressed and the ChallengeName property set to ChallengeNameType.NEW_PASSWORD_REQUIRED.

## Current Behavior

PasswordResetRequiredException is thrown.

## Steps to Reproduce (for bugs)

Reset the Cognito user's password via AWS Cognito so it must be changed on next login, then attempt login.

## Your Environment
AWSSDK.Core v4.0.30319
AWSSDK.Extensions.CognitoAuthentication v4.0.30319

**Comment by rogerioyuuki** [comment]
I think this is consistent with the documentation: https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_InitiateAuth.html#API_InitiateAuth_ResponseElements

> NEW_PASSWORD_REQUIRED: For users which are required to change their passwords after successful first login. This challenge should be passed with NEW_PASSWORD and any other required attributes.

> PasswordResetRequiredException
This exception is thrown when a password reset is required.
HTTP Status Code: 400

However this documentation was very hard to find, so that might add to the confusion.

**Comment by ashishdhingra** [comment]
Hi @iainb123, 

Please confirm if the above guidance about the documentation resolves the issue.

Thanks,
Ashish

**Comment by iainb123** [comment]
Sorry Ashish, this was a couple of years ago - I don't remember this very well, but I don't think the guidance solves the problem of there being no SessionID available.

**Comment by ashishdhingra** [comment]
Hi @iainb123, The guidance specifies that the behaviour is consistent as per documentation. It's just that the scenario needs to be handled differently in code with challenge type NEW_PASSWORD. If possible, please try to implement this scenario with new challenge type and confirm if it solves the issue.

**Comment by MosCD3** [comment]
Who on earth closed this issue? still no valid solution for that
