### ISSUE TITLE
Is there a code example on how to refresh tokens for the .Net SDK?

### ISSUE THREAD

**Issue by azahran007** [aws/aws-sdk-net-extensions-cognito#37]
I am unable to automatically refresh tokens with the .Net SDK, although this seems a no issue in the iOS and JS SDKs. Is there any code sample that shows how to do that properly?

**Comment by walshj19** [comment]
See the referenced pull request for an example. #38

**Comment by klaytaybai** [comment]
Thanks @walshj19.  @azahran007, were you able to get it working?

**Comment by azahran007** [comment]
It worked, thanks @walshj19 !

**Comment by SETSinsperion** [comment]
Greetings @azahran007 @walshj19 , I hope you have a good day, I also use .NET SDK for a C# WinForms application, I'm running long-duration S3 uploads, more than 1 hour, with files >1.91 GB, with a method that provides CognitoAWSCredentials object. Sometimes file uploads to S3, and anothers doesn't. Tests that I'm doing are uploads that took 2 hours until showed me exceptions with a file with 10 GB of size with network speed up to 5-7 Mbps, I try Low-Level API Multipart Upload and TransferUtility. I supposed the refresh token is the solution. During the multipart upload that my application is doing, is enough to call to the example method to refresh the token that contains in my CognitoAWSCredentials object? Thanks in advance for your support.

**Comment by azahran007** [comment]
@SETSinsperion sorry the response took too long. I am not sure if this is the solution for a long upload as you would need to refresh the taken midway. If you have already figured out the solution it would be helpful if you share it.

Thanks and sorry again!

Just in case it helps, below is my code:

 user.SessionTokens = new CognitoUserSession(null, null, RefreshToken, DateTime.Now, DateTime.Now.AddHours(1));

 InitiateRefreshTokenAuthRequest refreshRequest = new InitiateRefreshTokenAuthRequest()
 {
     AuthFlowType = AuthFlowType.REFRESH_TOKEN_AUTH
 };

 AuthFlowResponse authResponse = await user.StartWithRefreshTokenAuthAsync(refreshRequest);

 if (authResponse == null || authResponse.AuthenticationResult == null)
 {
     logger.Error("Refreshtoken Authentication failed");
     return;
 }

 IdToken = authResponse.AuthenticationResult.IdToken;

 //important in order to update the credentials object used  with the S3 component
 string _identityId = await GetAWSCredentials(IdToken);

**Comment by SETSinsperion** [comment]
Greetings @azahran007 and I hope you have a good day. No worries, I was expecting this late answer due to this issue was closed. Thank you for the code, and I still have the problem with long uploads/downloads due to daily activities, so if I get the answer to I'll show you to all who needs or has this situation.
