### ISSUE TITLE
Enable Advanced Security in Xamarin

### ISSUE THREAD

**Issue by Devashish007** [aws/aws-sdk-net-extensions-cognito#39]
Hi,

According to [this](https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-settings-viewing-advanced-security-app.html) you can enable Advanced Security for JS, iOS and Android but there is no mention for Xamarin.

Is there any way to enable the same? 

Thanks !

**Comment by niraj-bpsoftware** [comment]
Same question here.

**Comment by assyadh** [comment]
This is currently not supported, as this library builds on top of the .NET SDK.

**Comment by ashishdhingra** [comment]
Hi @Devashish007,

Based on input from @assyadh, please confirm if this issue could be closed.

Thanks,
Ashish
