### ISSUE TITLE
TOTP support

### ISSUE THREAD

**Issue by jeff-heienickle** [aws/aws-sdk-net-extensions-cognito#55]
I am attempting to set up a user pool with Multi-Factor Authentication and allow users to select a Time-based One-time Password using Google Authenticator. How do you respond to a challenge of type SOFTWARE_TOKEN_MFA using AWS .Net SDK? 

ASP.Net Core 3 with Identity
Amazon.Extensions.CognitoAuthentication Version=1.0.4

**Comment by NGL321** [comment]
Hi @jeff-heienickle,

After looking through this support library, it appears that unfortunately at the moment there is no wrapper for responding to a `SOFTWARE_TOKEN_MFA` challenge, as you can see [here](https://github.com/aws/aws-sdk-net-extensions-cognito/blob/master/src/Amazon.Extensions.CognitoAuthentication/CognitoUserAuthentication.cs).

If you would like to see how to respond to the challenge without the cognito extensions, please look at the [Cognito Identity Provider library](https://github.com/aws/aws-sdk-net/tree/master/sdk/src/Services/CognitoIdentityProvider) in the main .NET SDK.

However, implementing said wrapper seems fairly simple, so I can push a fix, then get back to you. Alternatively, if you feel like contributing, feel free to put in a PR with the changes, and I can review it. 
After added this, implementing would be as simple as following the [MFA instructions from the README](https://github.com/aws/aws-sdk-net-extensions-cognito#authenticating-with-multiple-forms-of-authentication).

Please let me know if this helps answer your question, and if you would like to implement this yourself, or see it implemented, and I will close the issue.

😸 😷
