### ISSUE TITLE
warning NU1608: Detected package version outside of dependency constraint: Amazon.Extensions.CognitoAuthentication 1.0.3 requires AWSSDK.CognitoIdentity (>= 3.3.100 && < 3.4.0) but version AWSSDK.CognitoIdentity 3.5.0.4 was resolved

### ISSUE THREAD

**Issue by hounddog22030** [aws/aws-sdk-net-extensions-cognito#57]
There has been an update to AWSSDK.Core from 3.4 to 3.5.  I'm using a lot of AWSSDK libraries and some are bringing 3.5 in.  The dependencies for this project are somewhere locked to AWSSDK.Core 3.4.  This is bringing a lot of grief.  Can the dependencies be updated to allow for 3.5?

warning NU1608: Detected package version outside of dependency constraint: Amazon.Extensions.CognitoAuthentication 1.0.3 requires AWSSDK.CognitoIdentity (>= 3.3.100 && < 3.4.0) but version AWSSDK.CognitoIdentity 3.5.0.4 was resolved

**Comment by johnboker** [comment]
Same problem here:

```
warning NU1608: Detected package version outside of dependency constraint: AWSSDK.SimpleSystemsManagement 3.3.102.2 requires AWSSDK.Core (>= 3.3.101.9 && < 3.4.0) but version AWSSDK.Core 3.5.1.6 was resolved.
warning NU1608: Detected package version outside of dependency constraint: AWSSDK.CloudWatchLogs 3.3.100.39 requires AWSSDK.Core (>= 3.3.103.2 && < 3.4.0) but version AWSSDK.Core 3.5.1.6 was resolved.
warning NU1608: Detected package version outside of dependency constraint: AWSSDK.SimpleSystemsManagement 3.3.102.2 requires AWSSDK.Core (>= 3.3.101.9 && < 3.4.0) but version AWSSDK.Core 3.5.1.6 was resolved.
warning NU1608: Detected package version outside of dependency constraint: AWSSDK.CloudWatchLogs 3.3.100.39 requires AWSSDK.Core (>= 3.3.103.2 && < 3.4.0) but version AWSSDK.Core 3.5.1.6 was resolved.
```

**Comment by hounddog22030** [comment]
I updated to 1.0.4 and then "bulldogged" my way thru updating every Amazon.* and AWSSDK.* package were using to the latest (3.5, etc).  And it *mostly* went away (sometimes I get a weird resolve).  But there seems to be no configuration that 1.0.3 will work with anymore.

**Comment by johnboker** [comment]
@hounddog22030 thanks, i was just looking through my options and deleted my comment because i noticed there are upgrade paths i can take.  I would have left the comment had I known you replied so quickly.

**Comment by SrutiG** [comment]
#60

**Comment by ashishdhingra** [comment]
This should be fixed in [Amazon.Extensions.CognitoAuthentication 2.0.3](https://www.nuget.org/packages/Amazon.Extensions.CognitoAuthentication/2.0.3)
