### ISSUE TITLE
Aws cognito refresh problem

### ISSUE THREAD

**Issue by hussainamir** [aws/aws-sdk-net-extensions-cognito#65]
Hi, I try to refresh aws cognito token by using your code example. But refresh token got null value, and after one hour access token expire as usual.
So kindly how i can refresh token so that access id will not expire up to 30 days

**Comment by ashishdhingra** [comment]
Hi @hussainamir,

This has been fixed in the latest version [Amazon.Extensions.CognitoAuthentication 2.0.3](https://www.nuget.org/packages/Amazon.Extensions.CognitoAuthentication/). Please upgrade to the latest version of NuGet package.

Thanks,
Ashish
