### ISSUE TITLE
Aws coginto refresh token problem

### ISSUE THREAD

**Issue by hussainamir** [aws/aws-sdk-net-extensions-cognito#66]
Dear @ashishdhingra ,
 I am using latest version of Amazon.Extensions.CognitoAuthentication" version="2.0.3" targetFramework="net472"
I still I am facing same problem cognito token expire after one hour (also after refresh). I am using

1. Get coginto user information by using user name and password
2. Refresh cognito token
3. Get cognito user credentials by using this method ` var credentials=user.GetCognitoAWSCredentials(FED_POOL_ID, new AppConfigAWSRegion().Region);`
4. Get AccessKey, SecretKey,Token from "credentials" variable in step 3, by using 
    ` var AccessKey= credentials.GetCredentials().AccessKey`,
     `var SecretKey= credentials.GetCredentials().SecretKey`,
    `var Token=  credentials.GetCredentials().Token`.

5. use these credentials information and intialize 
  `Client = new AmazonIotDataClient(string awsAccessKeyId, string awsSecretAccessKey, string awsSessionToken, string serviceUrl)`;
    
By using these step my credentials expire after one hour.

**if I use `Client =new  AmazonIotDataClient(string serviceUrl, AWSCredentials credentials)`;**

**then it's working fine. but in my case i want to use accesskey, secretKey, and token for third party API**

 Here I also want to share a another problem. Although I have set access token expiration time 1000 min or 5mint but my token will expire after one hour.
I am sending some screen shots
Please check it where I doing mistake.
 
![4](https://user-images.githubusercontent.com/36883634/105146757-a1f13800-5b00-11eb-9e52-35b8c5d40ebb.PNG)
![1](https://user-images.githubusercontent.com/36883634/105146235-0bbd1200-5b00-11eb-8a4c-41035a7f5889.PNG)
![2](https://user-images.githubusercontent.com/36883634/105146237-0c55a880-5b00-11eb-9846-c2084b0aeddd.PNG)
![3](https://user-images.githubusercontent.com/36883634/105146240-0cee3f00-5b00-11eb-8b90-def957523ea6.PNG)

**Comment by ashishdhingra** [comment]
Hi @hussainamir,

The problem where RefreshToken was lost when using the REFRESH_TOKEN auth flow was fixed in [2.0.3](https://www.nuget.org/packages/Amazon.Extensions.CognitoAuthentication/) of `Amazon.Extensions.CognitoAuthentication`. I think the other issue you mentioned about access token time expiration is the known issue and I saw some workaround in some old GitHub issue. Let me try to find more details for this issue and get back to you.

Thanks,
Ashish

**Comment by hussainamir** [comment]
@ashishdhingra  
Thanks for your fast response. 
Refresh token is working fine when I use this method to initialize this class object 

`=new AmazonIotDataClient(string serviceUrl, AWSCredentials credentials)'
But when I want to initialize same class object with other method 
`Client = new AmazonIotDataClient(string awsAccessKeyId, string awsSecretAccessKey, string awsSessionToken, string serviceUrl); `
Then token expire after one hour.

Here i am.facing two problems 
1) refresh token problem
2) Although I have set 1000 mint for token expiration time but it expiry after one hour .


Thanks: 
Hussain

**Comment by ashishdhingra** [comment]
Hi @hussainamir,

I got it. The correct way to use Cognito credentials to access AWS services is listed in the example in section `Use AWS Resources after Authentication` at [Amazon CognitoAuthentication Extension Library Examples](https://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/cognito-authentication-extension.html). You need to use `CognitoAWSCredentials` object in the service client constructor.

The constructor you are trying to use is different one which uses temporary session credentials (e.g. credentials from EC2 instance metadata service). For more details about session credentials, please refer [Requesting temporary security credentials](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp_request.html). Hope this provides some guidance.

Thanks,
Ashish

**Comment by hussainamir** [comment]
@ashishdhingra 
How I can increase the time of temporary token? 

Because I am using these credential for third party Mqtt API to subscribe data from aws iot core. 

Or can I update temporary credential after one hour? This will work?

`var AccessKey=credentials.GetCredentials().AccessKey,`
`var SecretKey=credentials.GetCredentials().SecretKey,`
`var Token= credentials.GetCredentials().Token`.

I am using third party Mqtt library because amazon didn't have any c# API to subscribe mqtt topics.

If amazon develop Mqtt API to subscribe mqtt topic then it will be best for us.
Amazon have same mqtt API in python where user can subscribe data from aws iot core.
I already have created this feature request on  aws .net sdk repository but no one reply me.

**Comment by ashishdhingra** [comment]
> @ashishdhingra
> How I can increase the time of temporary token?
> 
> Because I am using these credential for third party Mqtt API to subscribe data from aws iot core.
> 
> Or can I update temporary credential after one hour? This will work?
> 
> `var AccessKey=credentials.GetCredentials().AccessKey,`
> `var SecretKey=credentials.GetCredentials().SecretKey,`
> `var Token= credentials.GetCredentials().Token`.
> 
> I am using third party Mqtt library because amazon didn't have any c# API to subscribe mqtt topics.
> 
> If amazon develop Mqtt API to subscribe mqtt topic then it will be best for us.
> Amazon have same mqtt API in python where user can subscribe data from aws iot core.
> I already have created this feature request on aws .net sdk repository but no one reply me.

Temporary session token has limited timespan. After expiration, you need to re-fetch the temporary credentials. 
- The page [Making requests using IAM user temporary credentials - AWS SDK for .NET](https://docs.aws.amazon.com/AmazonS3/latest/dev/AuthUsingTempSessionTokenDotNet.html) lists an example on how to use temporary session credentials.
- The page [AWS Security Token Service -> GetSessionToken](https://docs.aws.amazon.com/STS/latest/APIReference/API_GetSessionToken.html) documents details about Session Duration.

As pointed out by you, you need to have refresh/retry logic in place to request temporary session credentials after expiration.

Hope this helps. If this provides necessary guidance, please confirm if we could close this issue.

Thanks,
Ashish

**Comment by hussainamir** [comment]
Dear @ashishdhingra Thanks for your guidance.
 
you can close this issue, If I get any problem regarding aws cognito in future then I will let you know.

Thanks
Hussain
