### ISSUE TITLE
Recent change to use DateTime.UtcNow was a breaking change (at least for our application)

### ISSUE THREAD

**Issue by rib** [aws/aws-sdk-net-extensions-cognito#77]
## Description

I just wanted to highlight this recent change to switch all usage of `DateTime.Now` to be `DateTime.UtcNow` was a breaking change for our application and potentially also other applications that may use apis like `DateTime.Subtract()` on any of the DateTime values exposed by this api.

In our case the issue was that we had some code like this for checking how many seconds were left before a token would expire:
```csharp
var accessTimeLeft = user.SessionTokens.ExpirationTime.Subtract(DateTime.Now).TotalSeconds;
```

but the problem here is that it assumes that the ExpirationTime uses the same timezone as `DateTime.Now` (otherwise `DateTime.Subtract()` doesn't really have meaningful / expected results.

## Resolution

I mean to be fair our code probably shouldn't have been making any assumption about the timezone used and can easily be updated so that we aren't dependent on the timezone used internally but still since this was changed recently maybe it would be good to add some clear documentation about the change somewhere as a potential warning in case anyone else has unwittingly made their app dependent on the old behaviour.

---

This is a :bug: bug-report

**Comment by rib** [comment]
Notably another place where this change matters is in case an application constructs its own `CognitoUserSession()` where now Extensions.CognitoAuthentication shouldn't be making any assumption about the timezone that's being used.

Specifically here for example:
https://github.com/aws/aws-sdk-net-extensions-cognito/blob/ddddb18296f88bd129e5ae52d40c6f021ed1c7db/src/Amazon.Extensions.CognitoAuthentication/CognitoUserSession.cs#L74

The documentation for `DateTime.CompareTo()` notes that it only really makes sense to compare DateTime values of the same kind in the same timezone, so perhaps an explicit `.ToUniversalTime()` should be added here to be sure it's checking like with like.

**Comment by rib** [comment]
For reference this other issue https://github.com/aws/aws-sdk-net-extensions-cognito/issues/76 shows an example for why we currently also construct our own `CognitoUserSession` state sometimes and notably we had been using local `DateTime` values up until now:

**Comment by ashishdhingra** [comment]
Hi @rib,

Good morning.

Thanks for reporting the side-effect of the recent change to use `DateTime.UtcNow`. The change was implemented since the `ExpirationTime` returned by the Cognito service is in UTC time. I agree there should be some kind of documentation update where user is able to pass ExpirationTime for some scenarios (like the RefreshToken as you mentioned). This is perhaps a change in `Readme` to add a note about the ExpirationTime.

Thanks,
Ashish

**Comment by rib** [comment]
Hi,

Thanks for reviewing this.

When I first described this issue I hadn't realised that Extensions.CognitoAuthentication is also making assumptions about the timezone of datetime values internally (E.g. within `IsValid()`).  I also hadn't realised that the README even shows reference code that uses `DateTime.UtcNow` to construct fake session tokens and previously the same reference code used `DateTime.Now`. (This is the example you shared with me: https://github.com/aws/aws-sdk-net-extensions-cognito#authenticating-using-a-refresh-token-from-a-previous-session)

I think this makes the issue a bit more serious imho than just a README change.

Any applications that followed the previous README reference code will be passing in local timezone datetime values and it wouldn't be valid to use CompareTo to check those against the internal utc datetime.

It really looks like `IsValid()` needs to be updated to not depend on the timezone to help ensure existing applications continue to work as previously documented. The check can simply call `.ToUniversalTime()` for example to guarantee that the datetime being compared is in the expected timezone.

Maybe it would also be worth reviewing the recent UtcNow change to try and check if there are any other instances where comparisons are made and they need to make sure both sides of the comparison are using the utc timezone.

Thanks again for looking at this!

**Comment by ashishdhingra** [comment]
Discussed with developer. The `CognitoUSerSession` constructor is also used internally by this library to use the values returned by Cognito service. The `ExpirationTime` value returned by Cognito service is in UTC and hence, we could not simply use `.ToUniversalTime()`. This is the Readme change.

**Comment by rib** [comment]
`.ToUniversalTime()` just makes sure that the datevalue is in utc, in case an app has passed a datevalue that's in local time so it's perfectly safe for it to be called in cases where UtcNow is used internally.

The problem isn't with the internal usage (that's ok) the problem is that `CognitoUserSession` is also public API and this project previously documented that applications could pass a local datetime and so now there's no guarantee whether `IsValid()` will receive a local or a utc datetime value here.

Please check this a bit closer - I'm quite confident that this isn't just a Readme issue. Luckily after spending time debugging why my application was broken I can convert my own code that was previously using `DateTime.Now` to use `DateTime.UtcNow` to be consistent with the new internal expectation but it's quite likely this change has broken (or is going to break when they next upgrade this dependency) other applications that followed the previous documentation that showed passing `DateTime.Now` into the public `CognitoUserSession` constructor.

**Comment by rib** [comment]
(To clarify - calling `.ToUniversalTime()` will simply return the same value if the the datetime value is already in the UTC timezone, so it should be perfectly safe for the internal usage - it just makes sure the code can handle applications that have passed in a local datetime value as was previously recommended in the projects documentation)

**Comment by normj** [comment]
@rib If I understand what you are saying is users that are directly calling the `CognitioUserSession` constructor passing in their own expiration date there is no guarantee that DateTime is in UTC. I would agree that is a problem and we should just call `.ToUnversalTime()` on the passed in timestamp which will be a noop for DateTimes that are already UTC.

**Comment by rib** [comment]
Right, that's the problem. Our application was passing in a local datetime value (which is previously what Extensions.CognitoAuthentication was expecting).

Considering the interaction with issue #76 I guess it's also very likely there are multiple apps in the wild (like ours) that have been following the previous README guidance to pass in a local datetime value for being able to refresh access tokens: https://github.com/aws/aws-sdk-net-extensions-cognito/blob/8b934dde5e142dfbacab4b04e69592439137a656/README.md#authenticating-using-a-refresh-token-from-a-previous-session

**Comment by ashishdhingra** [comment]
This is fixed in [Amazon.Extensions.CognitoAuthentication 2.2.2](https://www.nuget.org/packages/Amazon.Extensions.CognitoAuthentication/2.2.2)
