### ISSUE TITLE
Extensions CognitoAuthentication Documentation

### ISSUE THREAD

**Issue by marck0zz** [aws/aws-sdk-net-extensions-cognito#81]
Hello all!!

Is any documentation about the Extension CognitoAuthentication API like the [AWS SDK for .NET API Reference](https://docs.aws.amazon.com/sdkfornet/v3/apidocs/) ??

I'm interested in the login exceptions on "authFlowResponse" in order to give feedback to my users about what is goin on.

Thank you in advance.

**Comment by ashishdhingra** [comment]
Hi @marck0zz,

Good morning.

Thanks for posting guidance question.

Unfortunately, we do not have Cognito Extensions API documentation similar to AWS SDK for .NET API Reference](https://docs.aws.amazon.com/sdkfornet/v3/apidocs/). However, as Readme mentions, this library introduces/uses 2 dependencies:
- [AWSSDK.CognitoIdentity](https://www.nuget.org/packages/AWSSDK.CognitoIdentity/): [API reference](https://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/CognitoIdentity/NCognitoIdentity.html)
- [AWSSDK.CognitoIdentityProvider](https://www.nuget.org/packages/AWSSDK.CognitoIdentityProvider/): [API reference](https://docs.aws.amazon.com/sdkfornet/v3/apidocs/items/CognitoIdentityProvider/NCognitoIdentityProvider.html)

These could be the good references on what .NET SDK API(s) are invoked behind the scenes. Additionally, [Cognito Service API reference](https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-reference.html) is a good reference for determining the requirements and exceptions thrown by actual service API operation(s).

Hope this helps.

Thanks,
Ashish

**Comment by marck0zz** [comment]
Thanks a lot.

I'll take a look at those links

**Comment by ashishdhingra** [comment]
Closing this issue. Feel free to open new one in case there are more questions or guidance required.
