### ISSUE TITLE
A deadlock occurs with Android and C# when trying to create a provider with Amazon.CognitoIdentityProvider.AmazonCognitoIdentityProviderClient

### ISSUE THREAD

**Issue by DominusDRR** [aws/aws-sdk-net-extensions-cognito#84]
## Description
Hi.

I'm using the AWS Samples C# project named aws-cognito-dot-net-desktop-app as a reference:

https://github.com/aws-samples/aws-cognito-dot-net-desktop-app

The code of this project I am using it with C # and WPF and it works correctly (app for desktop PC).

Now, I'm doing the exact same thing but with Android and C# in Visual Studio.

When you want to register a user, the task called SignUpUser is executed, but when trying to create a provider with Amazon.CognitoIdentityProvider.AmazonCognitoIdentityProviderClient the code remains frozen in that line (deadlock)

This is an image of where the problem happens:

![image](https://user-images.githubusercontent.com/43682132/142537206-6cad9530-0b7d-446b-a95a-1b175311af12.png)

No exception or error message occurs.

It happens both in a real mobile phone and in a virtual phone.

It is as if some permission or something else needs to be enabled, even though internet and wifi permissions are enabled in the manifest.

## Reproduction Steps
1. Create a project of type Xamarin (Not Xamarin Forms) with Visual Studio 2019

2. Copy or create the CognitoHelper class in the project, it is the same as aws-cognito-dot-net-desktop-app.

3. Do not forget to install all the packages that correspond to Amazon ()using Amazon.CognitoIdentity, using Amazon.S3.Model, etc)

4. From another class you can invoke the task of registering a user as follows:

CognitoHelper helper = new CognitoHelper();
bool success = await helper.SignUpUser("UserName", "passwword", "userEmail@gmail", "123456789");

5. The code remains in a deadlock in AmazonCognitoIdentityProviderClient provider =
                    new Amazon.CognitoIdentityProvider.AmazonCognitoIdentityProviderClient(new Amazon.Runtime.AnonymousAWSCredentials());.

### Environment

* Build Version: 2.2.2
* OS Info: Windows 10 64 bits 20H2
* Build Environment: Microsoft Visual Studio Community 2019 Versión 16.11.3
* Targeted .NET Platform:  Android 11 (API 30-R)

## Resolution

---

This is a :bug: bug-report

**Comment by ashishdhingra** [comment]
Hi @DominusDRR,

Good morning.

Could you please advise on how your region is configured for your Xamarin app?

Thanks,
Ashish

**Comment by DominusDRR** [comment]
> Hi @DominusDRR,
> 
> Good morning.
> 
> Could you please advise on how your region is configured for your Xamarin app?
> 
> Thanks, Ashish

Hi. Thanks for writting.

It seems that I found a solution few minutes ago.

I got an example for Xamarin. Forms of this link:

[https://github.com/Pietervdw/xamarinforms-awscognito](url)

When reviewing the code and seeing how a provider is created, I changed the code to as follows:

Amazon.CognitoIdentityProvider.AmazonCognitoIdentityProviderClient provider = new Amazon.CognitoIdentityProvider.AmazonCognitoIdentityProviderClient(new AnonymousAWSCredentials(), RegionEndpoint.USEast1);

Now the code doesn't freeze and goes to the next line:

![image](https://user-images.githubusercontent.com/43682132/142689795-54d949cb-2eec-4ef4-98ea-470287d48a3a.png)

I need to keep going through the rest of the code to determine other possible issues

**Comment by ashishdhingra** [comment]
@DominusDRR Thanks for confirming. Changing this to `guidance` issue. Please close this issue once you are done scanning through rest of the code, OR, confirm if we could close this now since you have identified the solution.

**Comment by DominusDRR** [comment]
> hanks for confirming. Changing this to `guidance` issue. Please close this issue once you are done scanning through rest of the code, OR, confirm if we could close this now since you have identified the solution.

Hi.

Confirmed, where to create a provider must be as follows: (Obviously the region must be correct)

AmazonCognitoIdentityProviderClient(new Amazon.Runtime.AnonymousAWSCredentials(), RegionEndpoint.YourRegionAWS;

Process to close the case. Thanks again.
