### ISSUE TITLE
Missing Authentication Token when  trying to use ListUsersRequest

### ISSUE THREAD

**Issue by TMW81** [aws/aws-sdk-net-extensions-cognito#95]
### Describe the bug

I got the error, when  trying to use ListUsersRequest (in forgotten password flow [](https://referbruv.com/blog/implementing-cognito-forgot-password-and-update-profile-in-aspnet-core-using-aws-sdk/#:~:text=Reset%20a%20user%E2%80%99s%20forgotten%20password%20based%20on%20Email%20address%20aka%20Forgot%20Password%20Flow%3A))

**Missing Authentication Token Amazon.Runtime.Internal.HttpErrorResponseException: Exception of type 'Amazon.Runtime.Internal.HttpErrorResponseException' was thrown.**
```
 private async Task<ListUsersResponse> FindUsersByEmailAddress(string mail)
        {
            ListUsersRequest listUsersRequest = new ListUsersRequest
            {
                UserPoolId = _cognitoCredentials.UserPoolId, 
                Filter = $"email=\"{mail}\""
            };
            return await _provider.ListUsersAsync(listUsersRequest);
        }
```

### Expected Behavior

No error, get a list of registered users from Cognito.

### Current Behavior

Error is thrown: 
**Missing Authentication Token Amazon.Runtime.Internal.HttpErrorResponseException: Exception of type 'Amazon.Runtime.Internal.HttpErrorResponseException' was thrown.**

### Reproduction Steps

Use this method to get list of available users: 

```
private async Task<ListUsersResponse> FindUsersByEmailAddress(string mail)
        {
            ListUsersRequest listUsersRequest = new ListUsersRequest
            {
                UserPoolId = _cognitoCredentials.UserPoolId, 
                Filter = $"email=\"{mail}\""
            };
            return await _provider.ListUsersAsync(listUsersRequest);
        }

```

### AWS .NET SDK and/or Package version used

Unity 2021.3.9
Aws sdk .net

### Targeted .NET Platform

.Net 4.x

### Operating System and version

Windows 11

**Comment by ashishdhingra** [comment]
Hi @TomaszWozniakMosina,

Good morning.

Unfortunately, the issue is not reproducible using the below code:
```C#
using Amazon.CognitoIdentityProvider;
using Amazon.CognitoIdentityProvider.Model;
using System.Threading.Tasks;

namespace TestConsoleApp_NetFramework
{
    internal class Program
    {
        static string userPoolId = "<<user-ppol-id>>";

        static void Main(string[] args)
        {
            string email = "<<valid-email-address>>";
            var response = ListCognitoUsers(userPoolId, email).Result;
        }

        private static async Task<ListUsersResponse> ListCognitoUsers(string userPoolId, string email)
        {
            AmazonCognitoIdentityProviderClient client = new AmazonCognitoIdentityProviderClient(Amazon.RegionEndpoint.USEast2);
            var request = new ListUsersRequest() { UserPoolId = userPoolId, Filter = $"email=\"{email}\"" };
            return await client.ListUsersAsync(request);
        }
    }
}

```

Please check if you have configured the AWS credentials properly (with proper IAM policy/permission to list users) in your profile chain to access Cognito service.

Thanks,
Ashish
